image: php:8.0

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/

before_script:
  # Install system components
  - apt-get update -qy
  - apt-get install -y git zip unzip

  # Install PHP extensions
  #- docker-php-ext-install -j$(nproc) gd

  # Install Composer
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php');"

  # Install application libraries
  - php composer.phar install

stages:
  - test

test:
  stage: test
  environment:
    name: test
  only:
    - master
  script:
    - echo "Running tests"
    - vendor/bin/nunjuck tests/cases
