name: "Tests"

on:
  pull_request:
    paths-ignore:
      - ".docs/**"
  push:
    branches:
      - "*"
  schedule:
    - cron: "0 8 * * 1" # At 08:00 on Monday

env:
  extensions: "json"

jobs:
  tests:
    name: "Tests"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        php: [ "8.4", "8.3", "8.2", "8.1" ]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: "${{ env.extensions }}"
      - run: composer install --no-progress --prefer-dist
      - run: make tests
        shell: bash
      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: tests/**/output


  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: "${{ env.extensions }}"
      - run: composer install --no-progress --prefer-dist
      - run: make coverage
        shell: bash
      - run: wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.4.3/php-coveralls.phar
      - env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: php php-coveralls.phar --verbose --config tests/.coveralls.yml